/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.*;
import javax.swing.JOptionPane;
import Class.*;
import java.sql.Timestamp;


/**
 *
 * @author quanganh
 */
public class FormPayment extends javax.swing.JFrame {

    /**
     * Creates new form FormPayment
     */
    private static Integer mathuemay;
    private static double tongtien;
    private static int mamay;
    
    private KhachHangDao khachHangDao = new KhachHangDao();
    public FormPayment(Integer mathuemay, double tongtien, int mamay) {
        this.mathuemay = mathuemay;
        this.tongtien = tongtien;
        this.mamay = mamay;
        initComponents(); 
        txt_mathuemay.setText(mathuemay.toString());
        txt_tongtien.setText(String.valueOf(tongtien));   
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txt_mathuemay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_makhachhang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_diemtichluy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_sodiemsudung = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Mã thuê máy");

        txt_mathuemay.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_mathuemay.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Tổng tiền");

        txt_tongtien.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_tongtien.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng");

        txt_makhachhang.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Số điểm tích lũy");

        txt_diemtichluy.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_diemtichluy.setText("0");
        txt_diemtichluy.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Số điểm sử dụng");

        txt_sodiemsudung.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_sodiemsudung.setText("0");

        jButton1.setText("Thanh toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sodiemsudung, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_diemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_mathuemay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mathuemay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_diemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_sodiemsudung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txt_makhachhang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã khách hàng!");
            return;
        }
        Object kh = khachHangDao.getDiemTichLuyByMaKhachHang(Integer.parseInt(txt_makhachhang.getText()));
        if (kh instanceof Integer) {
            txt_diemtichluy.setText(kh.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không tồn tại.");
            txt_makhachhang.setText("");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
        // Lấy số điểm sử dụng và số điểm tích lũy từ form
        int diemsudung = Integer.parseInt(txt_sodiemsudung.getText());
        int diemtichluy = Integer.parseInt(txt_diemtichluy.getText());
        
        // Kiểm tra nếu số điểm sử dụng lớn hơn số điểm tích lũy
        if (diemsudung > diemtichluy) {
            JOptionPane.showMessageDialog(rootPane, "Số điểm sử dụng không được lớn hơn số điểm tích lũy.");
            return;
        }
        
        // Tính tổng tiền cần thanh toán sau khi trừ số điểm sử dụng
        double tienThanhToan = tongtien - diemsudung;
        
        // Hiển thị số tiền cần thanh toán và yêu cầu xác nhận
        int confirmed = JOptionPane.showConfirmDialog(rootPane, 
            "Số tiền cần thanh toán là: " + tienThanhToan + " đồng\nBạn có muốn tiếp tục không?", 
            "Xác nhận thanh toán", JOptionPane.YES_NO_OPTION);
        
        // Nếu người dùng nhấn Yes (YES_OPTION), thực hiện thanh toán
        if (confirmed == JOptionPane.YES_OPTION) {
            ThueMay newObj = new ThueMay();
            newObj.setMaThueMay(mathuemay);
            newObj.setThoiGianKetThuc(new Timestamp(System.currentTimeMillis()));
            newObj.setTongChiPhi(tienThanhToan); // Gán tổng chi phí sau khi trừ điểm sử dụng
            
            // Kiểm tra nếu mã khách hàng không rỗng, set MaKhachHang
            if (!txt_makhachhang.getText().trim().isEmpty()) {
                newObj.setMaKhachHang(Integer.parseInt(txt_makhachhang.getText()));
            }
            
            // Gọi DAO để lưu thông tin thanh toán
            ThueMayDao thueMayDao = new ThueMayDao();
            thueMayDao.edit(newObj);
            
            // Thông báo thanh toán thành công
            JOptionPane.showMessageDialog(rootPane, "Thanh toán thành công");
            MayDao mayDao = new MayDao();
            mayDao.updateTrangThaiMay(mamay, "Rảnh");
            if(!txt_makhachhang.getText().trim().isEmpty()){
                if(khachHangDao.addDiemTichLuy(Integer.parseInt(txt_makhachhang.getText()), (int)tienThanhToan*2/100)){
                    JOptionPane.showMessageDialog(rootPane, "Khách hàng đã đc cộng số điểm tích lũy: " + (int)tienThanhToan*2/100);
                    return;
                }
            }
            dispose();
        }
    } catch (Exception ex) {
        // Bắt lỗi và hiển thị thông báo lỗi
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPayment(mathuemay, tongtien, mamay).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txt_diemtichluy;
    private javax.swing.JTextField txt_makhachhang;
    private javax.swing.JTextField txt_mathuemay;
    private javax.swing.JTextField txt_sodiemsudung;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
